### PR TITLE
README: document how to use with secure boot

### PR DESCRIPTION
**Pull request by cole-h**
##### Checklist

- [x] Built with `cargo build`
- [x] Formatted with `cargo fmt`
- [x] Linted with `cargo clippy`
- [x] Ran tests with `cargo test`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [x] Added or updated relevant documentation (leave unchecked if not applicable)

---

Closes https://github.com/DeterminateSystems/bootspec/issues/53.
Closes https://github.com/DeterminateSystems/bootspec/issues/66.

This is a draft because I haven't actually tested it myself yet. I've run the tools manually, and they work as expected, but I haven't tried booting it, and probably won't (PTSD from a previous failed attempt at using Secure Boot years ago).

### CODE REVIEW

**Comment by grahamc** [comment]
There were a number of issues I found when testing this PR, I fixed most of them in the most recent commit. However, at the end of it, I still couldn't use this PR:

```
[installer/src/main.rs:134] &args = Args {
    toplevel: "/nix/store/ggy9k714g0yg52gcl5p137zff30hmxm1-nixos-system-hyperchicken-22.05.20211203.ee3794c",
    dry_run: false,
    generated_entries: "./systemd-boot-entries",
    timeout: Some(
        5,
    ),
    console_mode: "keep",
    configuration_limit: None,
    editor: true,
    verbosity: 0,
    install: false,
    esp: [
        "/boot",
    ],
    can_touch_efi_vars: true,
    bootctl: Some(
        "/nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/bin/bootctl",
    ),
    unified_efi: true,
    signing_info: Some(
        SigningInfo {
            signing_key: "/persist/secureboot/db.key",
            signing_cert: "/persist/secureboot/db.cert",
            sbsign: "/nix/store/djz3zdy7mkm6k6diayg4lk8pzd1fq5v7-sbsigntool-0.9.1/bin/sbsign",
            sbverify: "/nix/store/djz3zdy7mkm6k6diayg4lk8pzd1fq5v7-sbsigntool-0.9.1/bin/sbverify",
        },
    ),
}
Copied "/nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".
Copied "/nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".
Error: "systemd-boot-entries/efi/nixos/2zk5lzb044p5bk6ii6zc2r4x71kb2ack.efi could not be signed"
+ finish
```

I wonder if you have any insight?

**Comment by cole-h** [comment]
Nothing immediately comes to mind... Would you mind running the installer with `-vvvv`? There's a small amount of extra logging that might help pinpoint this. Maybe also comment out the null pipes at:

https://github.com/DeterminateSystems/bootspec/blob/c33be44ce91bba81e5d324ee230781c36f09c647/installer/src/secure_boot.rs#L30-L31

**Comment by cole-h** [comment]
Never mind, I can reproduce this. Investigating.

**Comment by grahamc** [comment]
It turns out I was passing the wrong file names :upside_down_face:  see #66.

However, now I can't boot because the bootloader is not signed!

```
/boot/EFI/systemd/systemd-bootx64.efi
warning: data remaining[84992 vs 96038]: gaps between PE/COFF sections?
warning: data remaining[84992 vs 96040]: gaps between PE/COFF sections?
No signature table present
Signature verification failed



/boot/EFI/BOOT/BOOTX64.EFI
warning: data remaining[84992 vs 96038]: gaps between PE/COFF sections?
warning: data remaining[84992 vs 96040]: gaps between PE/COFF sections?
No signature table present
Signature verification failed
```

**Comment by grahamc** [comment]
I used this script:

```
#!/usr/bin/env nix-shell
#!nix-shell -p openssl efitools sbsigntool shellcheck -i bash
# shellcheck shell=bash

set -eu

shellcheck "$0"

readonly target="$1"

if [ -e "$target" ]; then
    echo "$target already exists, but should not. Aborting!"
    exit 1
fi

# Verify we can make the target
mkdir -p "$target"
rmdir "$target"

scratch=$(mktemp -d -t tmp.XXXXXXXXXX)
function finish {
  rm -rf "$scratch"
}
trap finish EXIT

cd "$scratch"
mkdir -p ./{db,dbx,KEK,PK}
uuidgen --random > GUID.txt

(
    cd PK
    openssl req -newkey rsa:4096 -nodes -keyout PK.key -new -x509 -sha256 -days 3650 -subj "/CN=my Platform Key/" -out PK.crt
    openssl x509 -outform DER -in PK.crt -out PK.cer
    cert-to-efi-sig-list -g "$(< ../GUID.txt)" PK.crt PK.esl
    sign-efi-sig-list -g "$(< ../GUID.txt)" -k PK.key -c PK.crt PK PK.esl PK.auth
    sign-efi-sig-list -g "$(< ../GUID.txt)" -c PK.crt -k PK.key PK /dev/null rm_PK.auth
)

(
    cd KEK
    openssl req -newkey rsa:4096 -nodes -keyout KEK.key -new -x509 -sha256 -days 3650 -subj "/CN=my Key Exchange Key/" -out KEK.crt
    openssl x509 -outform DER -in KEK.crt -out KEK.cer
    cert-to-efi-sig-list -g "$(< ../GUID.txt)" KEK.crt KEK.esl
    sign-efi-sig-list -g "$(< ../GUID.txt)" -k ../PK/PK.key -c ../PK/PK.crt KEK KEK.esl KEK.auth
)

(
    cd db
    openssl req -newkey rsa:4096 -nodes -keyout db.key -new -x509 -sha256 -days 3650 -subj "/CN=my Signature Database key/" -out db.crt
    openssl x509 -outform DER -in db.crt -out db.cer
    cert-to-efi-sig-list -g "$(< ../GUID.txt)" db.crt db.esl
    sign-efi-sig-list -g "$(< ../GUID.txt)" -k ../KEK/KEK.key -c ../KEK/KEK.crt db db.esl db.auth
)

sbkeysync --pk --dry-run --verbose --keystore .

mkdir "$target"
mv ./* "$target/"
```

then copied the `*.auth` files to a USB disk and loaded them in to the firmware via the firmware UI.

Then I set:

```nix
  boot.loader.secureboot = {
    enable = true;
    signingKeyPath = "/persist/secureboot/db/db.key";
    signingCertPath = "/persist/secureboot/db/db.crt";
  };
```

and I now have secureboot!

**Pull request merged**
